// Package introspect builds an immutable snapshot of a PostgreSQL schema from
// pg_catalog / information_schema (D1).
//
// The catalog is the single source of truth for every identifier pgdesk emits.
// A request string is never concatenated into SQL; it is used only as a map key
// to resolve to a *Column whose Name came from pg_catalog (D3). The catalog is
// built once, is immutable, and is swapped atomically on Reload (D1).
package introspect

import (
	"slices"
	"strings"
)

// TypeCategory is pgdesk's coarse classification of a column's PostgreSQL type.
// It keys the filter operator whitelist (D3): operators are allowed per category,
// not per concrete type, so a new timestamp-like type behaves predictably.
type TypeCategory string

const (
	CatText      TypeCategory = "text"
	CatNumeric   TypeCategory = "numeric"
	CatTimestamp TypeCategory = "timestamp"
	CatBool      TypeCategory = "bool"
	CatEnum      TypeCategory = "enum"
	CatUUID      TypeCategory = "uuid"
	CatJSON      TypeCategory = "json"
	CatOther     TypeCategory = "other"
)

// Column is an immutable description of one table/view column.
type Column struct {
	// Name is the column name exactly as stored in pg_catalog. It is the ONLY
	// source of a column identifier that reaches SQL; request strings resolve to
	// this, never the other way around (D3).
	Name string
	// Position is the 1-based ordinal (attnum) for stable ordering.
	Position int
	// DataType is the fully-qualified PostgreSQL type name (e.g. "timestamptz").
	DataType string
	// Category is the coarse type classification used by the operator whitelist.
	Category TypeCategory
	// Nullable reports whether the column permits NULL.
	Nullable bool
	// HasDefault reports whether the column has a DEFAULT expression.
	HasDefault bool
	// IsGenerated reports whether the column is GENERATED (always computed).
	IsGenerated bool
	// IsIdentityAlways reports whether the column is GENERATED ALWAYS AS IDENTITY
	// (attidentity = 'a'). PostgreSQL forbids writing any value other than DEFAULT
	// to such a column, so it must be excluded from INSERT/UPDATE column lists
	// exactly like a generated column; otherwise every edit fails with SQLSTATE
	// 428C9. GENERATED BY DEFAULT AS IDENTITY ('d') is writable and is NOT flagged.
	IsIdentityAlways bool
	// EnumLabels holds the valid labels when Category == CatEnum, in sort order.
	// Filter values for enum columns are validated against this set (D3).
	EnumLabels []string
	// Comment is the column comment if present (used for field help text).
	Comment string
}

// IsEnum reports whether the column is an enum type with a known label set.
func (c *Column) IsEnum() bool { return c.Category == CatEnum && len(c.EnumLabels) > 0 }

// ValidEnumLabel reports whether v is one of the column's enum labels. It is
// used to fail closed on enum filter values that don't exist in the catalog.
func (c *Column) ValidEnumLabel(v string) bool {
	return slices.Contains(c.EnumLabels, v)
}

// ForeignKey describes a single-column-or-composite FK to another table. FK
// label display uses batched ANY($1) lookups, never generated JOINs (D4).
type ForeignKey struct {
	// Columns are the referencing columns on this table, in order.
	Columns []string
	// RefSchema and RefTable identify the referenced relation.
	RefSchema string
	RefTable  string
	// RefColumns are the referenced columns, positionally matching Columns.
	RefColumns []string
}

// UniqueConstraint is a unique constraint or unique index on a table. It is keyed
// by Name (the constraint/index name PostgreSQL reports in a 23505 error), so a
// unique violation can be mapped to the specific columns (D7).
type UniqueConstraint struct {
	Name    string
	Columns []string
}

// Table is an immutable description of a table or view plus the derived
// capabilities pgdesk needs.
type Table struct {
	Schema string
	Name   string
	// IsView is true for views and materialized views.
	IsView bool
	// Updatable reports whether UPDATE is possible against the relation. It is the
	// UPDATE capability specifically: true for ordinary tables, and for views that
	// are auto-updatable or trigger-updatable (pg_relation_is_updatable). A
	// non-updatable relation auto-disables the edit path (D6). Insert and Delete
	// are tracked separately so a view that supports only some operations exposes
	// exactly those (see Insertable/Deletable).
	Updatable bool
	// Insertable reports whether INSERT is possible (auto- or trigger-insertable).
	// It is distinct from Updatable: a view can be updatable but not insertable.
	Insertable bool
	// Deletable reports whether DELETE is possible (auto- or trigger-deletable).
	Deletable bool
	// HasXmin reports whether the relation exposes a selectable xmin system column,
	// i.e. it is a physical relation (ordinary/partitioned table or materialized
	// view). Views and foreign tables have no xmin; selecting it there errors, so
	// the default optimistic-concurrency strategy must not use xmin for them (O1).
	HasXmin bool
	// Comment is the relation comment if present.
	Comment string

	// columns is the ordered column list (by attnum).
	columns []*Column
	// byName resolves a column name to its *Column in O(1). This map is the
	// identifier-resolution gate for the whole query layer (D3).
	byName map[string]*Column

	// PrimaryKey is the ordered PK column set. It MAY be empty (views, unkeyed
	// tables); such resources are list-only until the user declares a key (D6).
	PrimaryKey []*Column

	// ForeignKeys are the outbound FK constraints on this table.
	ForeignKeys []*ForeignKey

	// UniqueConstraints are unique constraints/indexes, used to map 23505 errors
	// to specific columns (D7).
	UniqueConstraints []*UniqueConstraint
	uniqueByName      map[string][]string
}

// setUniques stores unique constraints and builds the name->columns lookup. It is
// called by the loader before the table is published; the table is immutable
// thereafter.
func (t *Table) setUniques(u []*UniqueConstraint) {
	t.UniqueConstraints = u
	t.uniqueByName = make(map[string][]string, len(u))
	for _, uc := range u {
		t.uniqueByName[uc.Name] = uc.Columns
	}
}

// UniqueColumns returns the columns covered by a named unique constraint/index,
// or (nil, false) if the name is unknown. Used to attach a 23505 unique violation
// to its specific field(s) (D7).
func (t *Table) UniqueColumns(constraintName string) ([]string, bool) {
	cols, ok := t.uniqueByName[constraintName]
	return cols, ok
}

// QualifiedName returns schema.name for lookups and logging (unquoted).
func (t *Table) QualifiedName() string { return t.Schema + "." + t.Name }

// Columns returns the ordered columns. The returned slice must not be mutated.
func (t *Table) Columns() []*Column { return t.columns }

// Column resolves a column name to its immutable *Column, or (nil, false) if the
// name is not a real column of this table. This is the primary identifier gate:
// unresolved names are rejected upstream with 400, never emitted as SQL (D3).
func (t *Table) Column(name string) (*Column, bool) {
	c, ok := t.byName[name]
	return c, ok
}

// HasKey reports whether the table has a usable primary key. Detail/edit/delete
// capabilities are derived from this (D6).
func (t *Table) HasKey() bool { return len(t.PrimaryKey) > 0 }

// NewTable assembles an immutable *Table, building the name-resolution map from
// cols. It is used by the loader and by tests; it is not part of the public API
// (this is an internal package). cols must be in ordinal order.
//
// Insertable, Deletable, and HasXmin are derived from the coarse (isView,
// updatable) inputs so existing callers keep working: an updatable relation is
// treated as fully insert/update/delete-capable, and a non-view is assumed to
// have xmin. The loader overrides all three with precise catalog values via
// setCaps; tests that need a specific shape can do the same.
func NewTable(schema, name string, isView, updatable bool, comment string, cols, pk []*Column, fks []*ForeignKey) *Table {
	byName := make(map[string]*Column, len(cols))
	for _, c := range cols {
		byName[c.Name] = c
	}
	return &Table{
		Schema:      schema,
		Name:        name,
		IsView:      isView,
		Updatable:   updatable,
		Insertable:  updatable,
		Deletable:   updatable,
		HasXmin:     !isView,
		Comment:     comment,
		columns:     cols,
		byName:      byName,
		PrimaryKey:  pk,
		ForeignKeys: fks,
	}
}

// setCaps overrides the per-operation write capabilities and xmin availability
// with precise catalog-derived values. It is called by the loader before the
// table is published; the table is immutable thereafter.
func (t *Table) setCaps(insertable, updatable, deletable, hasXmin bool) {
	t.Insertable = insertable
	t.Updatable = updatable
	t.Deletable = deletable
	t.HasXmin = hasXmin
}

// Catalog is an immutable snapshot of the introspected schema. It is built once
// and swapped atomically; readers hold a *Catalog for the life of a request so a
// mid-request Reload cannot shift the schema underneath them (D1).
type Catalog struct {
	// Schemas are the schema names that were introspected, in request order.
	Schemas []string
	// tables resolves "schema.name" to its *Table.
	tables map[string]*Table
	// order preserves discovery order for stable listing/logging.
	order []*Table
}

// NewCatalog assembles an immutable *Catalog from a set of tables, preserving
// discovery order. Used by the loader and by tests.
func NewCatalog(schemas []string, tables []*Table) *Catalog {
	m := make(map[string]*Table, len(tables))
	order := make([]*Table, 0, len(tables))
	for _, t := range tables {
		m[t.Schema+"."+t.Name] = t
		order = append(order, t)
	}
	return &Catalog{Schemas: schemas, tables: m, order: order}
}

// Table resolves a table by schema and name.
func (c *Catalog) Table(schema, name string) (*Table, bool) {
	t, ok := c.tables[schema+"."+name]
	return t, ok
}

// Tables returns every introspected relation in discovery order. The slice must
// not be mutated.
func (c *Catalog) Tables() []*Table { return c.order }

// categoryFor maps a PostgreSQL type name and pg_type.typcategory code to a
// pgdesk TypeCategory. typcat is the single-character pg_type.typcategory; name
// is the type name (already lower-cased, base type for arrays/domains resolved
// by the loader). Enum detection is driven by isEnum, since typcategory 'E' is
// authoritative but we also accept an explicit flag from the loader.
func categoryFor(name string, typcat byte, isEnum bool) TypeCategory {
	if isEnum || typcat == 'E' {
		return CatEnum
	}
	switch name {
	case "bool", "boolean":
		return CatBool
	case "uuid":
		return CatUUID
	case "json", "jsonb":
		return CatJSON
	}
	// Prefix checks catch the timestamp/time family and numeric width variants.
	switch {
	case name == "date",
		strings.HasPrefix(name, "timestamp"),
		strings.HasPrefix(name, "time"):
		return CatTimestamp
	}
	switch typcat {
	case 'B':
		return CatBool
	case 'N':
		return CatNumeric
	case 'D':
		return CatTimestamp
	case 'S':
		return CatText
	}
	return CatOther
}
